version: "3.8"
services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
    restart: always
    command: [ "./scripts/docker-entrypoint.sh" ]
    networks:
      - default
    volumes:
      - .:/src/app
      - /src/app/node_modules
  maildev:
    image: maildev/maildev
    container_name: maildev
    ports:
      - "1080:1080"
      - "1025:1025"
volumes:
  rabbit_data:
networks:
  default:
    external:
      name: rabbitmq_network