version: "3.8"
services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - postgres
    environment:
      - PORT=${PORT}
      - MODE=${MODE}
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    command: [ "./scripts/wait-for-postgres.sh", "./scripts/docker-entrypoint.sh" ]
    restart: "unless-stopped"
    ports:
      - "8081:8081"
    networks:
      - nesjs-network
    volumes:
      - .:/src/app
      - /src/app/node_modules

  postgres:
    image: postgres:14.4
    ports:
      - "5433:5433"
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    healthcheck:
      test: echo "SELECT 1" | psql -q -p 5433 -U postgres > /dev/null
      interval: 10s
      timeout: 1s
      retries: 3
    restart: always
    networks:
      - nesjs-network
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    command: postgres -c listen_addresses='*'

networks:
  nesjs-network:
volumes:
  pgdata: