version: "3.8"
services:
  rabbitmq:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - rabbit_data:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 1s
      retries: 3
    restart: always
    hostname: "rabbitmq"
    expose:
      - "5672"
      - "15672"
    networks:
      - default
volumes:
  rabbit_data:
networks:
  default:
    name: rabbitmq_network